import ScrollToTop from "@/source/components/ScrollToTop";
import Footer from "@/source/components/server/Footer";
import { inter, montserrat, openSans, roboto, tiroGurmukhi } from "@/source/config/fonts";
import Headers from "@components/Headers";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${openSans.className} ${tiroGurmukhi.className} ${roboto.className} ${inter.className}`}>
        <div className="bg-main-mobile md:bg-main">
          <Headers />
          {children}
          <Footer />
          <ScrollToTop />
        </div>
      </body>
    </html>
  )
}
